version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 10002:5432
    volumes:
      - ~/apps/postgres_db_boilerplate_example:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

      